-- =========================================================
-- Mr.Artist - Supabase Database Schema & Product Catalog
-- Run this script in your Supabase SQL Editor (1-Click Setup)
-- =========================================================

-- 1. Create 'artworks' table
CREATE TABLE IF NOT EXISTS public.artworks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    image_url TEXT NOT NULL,
    category TEXT DEFAULT 'landscape' NOT NULL, -- 'landscape', 'abstract', 'botanical', 'custom'
    format TEXT DEFAULT 'A4 Size (300GSM Board)' NOT NULL, 
    -- Formats:
    -- 'A4 Size 300GSM Board' (LKR 500)
    -- 'A3 Size 300GSM Board' (LKR 900)
    -- '12.5 x 24.5" Landscape 4mm (2600GSM) Board' (LKR 2,400)
    -- '12.5 x 18" x3 Triptych 4mm (2600GSM) Board' (LKR 2,900)
    -- 'Customizable Size & Design' (LKR 500+)
    price NUMERIC NOT NULL DEFAULT 500, -- Price in LKR
    tag TEXT DEFAULT '300 GSM Board',
    description TEXT
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.artworks ENABLE ROW LEVEL SECURITY;

-- 3. Allow Public Read Access (Anyone visiting the website can view artworks)
CREATE POLICY "Public Artworks are viewable by everyone" 
ON public.artworks FOR SELECT 
USING (true);

-- 4. Clean previous sample rows if re-running
TRUNCATE TABLE public.artworks;

-- 5. Insert Initial Sample Artworks into the Database
INSERT INTO public.artworks (name, image_url, category, format, price, tag, description)
VALUES
    (
        'Sahara Sunset Horizon',
        'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=85',
        'landscape',
        '12.5 x 18" x3 Triptych 4mm (2600GSM) Board',
        2900,
        '4mm Rigid Triptych Set',
        'Continuous panoramic landscape across three 12.5 x 18 inch rigid 4mm (2600GSM) boards. Delivers an architectural 3D depth effect.'
    ),
    (
        'Golden Coast Panoramic',
        'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=85',
        'landscape',
        '12.5 x 24.5" Landscape 4mm (2600GSM) Board',
        2400,
        '4mm Rigid Landscape Board',
        'Expansive 12.5 x 24.5 inch horizontal display mounted on heavy 4mm (2600GSM) rigid board.'
    ),
    (
        'Terracotta Abstract Geometry',
        'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1000&q=85',
        'abstract',
        'A3 Size 300GSM Board',
        900,
        'A3 300GSM Board',
        'Expressive textures in warm terracotta, cream, and charcoal printed on 300GSM fine art board.'
    ),
    (
        'Botanical Silhouette Study',
        'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=85',
        'botanical',
        'A4 Size 300GSM Board',
        500,
        'A4 300GSM Board',
        'Delicate foliage and warm earthy background tones printed on 300GSM premium art board.'
    ),
    (
        'Nordic Pine Valley',
        'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=1000&q=85',
        'landscape',
        '12.5 x 24.5" Landscape 4mm (2600GSM) Board',
        2400,
        '4mm Rigid Landscape Board',
        'Calm evergreen wilderness with soft atmospheric mist on 4mm heavy rigid board.'
    ),
    (
        'Minimalist Ceramic Form',
        'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=85',
        'abstract',
        'A4 Size 300GSM Board',
        500,
        'A4 300GSM Board',
        'Handcrafted pottery shapes and gentle lighting on 300GSM fine art board.'
    );
